// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guide: [
    {
      type: 'category',
      label: '📒 指南',
      collapsible: false,
      link: {
        type: 'doc',
        id: 'guide/intro',
      },
      items: [
        'guide/structure',
        {
          type: 'category',
          label: '📡 Host',
          collapsible: false,
          link: {
            type: 'doc',
            id: 'guide/host/intro'
          },
          items: [
            'guide/host/start',
            'guide/host/settings',
            'guide/host/toPublic',
          ]
        },
        {
          type: 'category',
          label: '🖥 网页控制台',
          collapsible: false,
          link: {
            type: 'doc',
            id: 'guide/webConsole/intro'
          },
          items: [
            'guide/webConsole/config'
          ]
        },
        {
          type: 'category',
          label: '🕹 实例插件',
          collapsible: false,
          link: {
            type: 'doc',
            id: 'guide/instance/intro'
          },
          items: [
            'guide/instance/config',
            'guide/instance/Serein',
            'guide/instance/MCDReforged',
          ]
        }
      ]
    },

  ],
  development: [
    {
      type: 'category',
      label: '🛠 开发',
      collapsible: false,
      link: {
        type: 'doc',
        id: 'development/intro'
      },
      items: [
        'development/client',
        {
          type: 'category',
          label: '🌌 逻辑',
          items: [
            {
              type: 'autogenerated',
              dirName: 'development/logic'
            }
          ]
        },
        {
          type: 'category',
          label: '📦 数据包',
          link: {
            type: 'doc',
            id: 'development/packet'
          },
          items: [
            'development/packet/members',
            'development/packet/additionalMembers',
            {
              type: 'category',
              label: '🔩 数据结构',
              link: {
                type: 'generated-index'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'development/packet/struct'
                }
              ]
            },
            {
              type: 'category',
              label: '🔔 事件',
              link: {
                type: 'generated-index'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'development/packet/event'
                }
              ]
            },
            {
              type: 'category',
              label: '⚔ 动作',
              link: {
                type: 'generated-index'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'development/packet/action'
                }
              ]
            }
          ]
        }
      ]
    }
  ],

};

module.exports = sidebars;
